export interface Activity {
    activityId: string; // auto generated by the server
    name: string;
    description: string;
    salePrice: number;
    currency: 'USD' | 'Euro';
    commissionRate: number; // in percentage
    commissionAmount: number; // in currency
    costPriceAdult: number; // in currency
    costPriceChild: number; // in currency
    costPriceBaby: number; // in currency
    costPriceTotal: number; // in currency
    createdBy: {
        uid: string; // from logged-in user
        name: string;
        email: string;
    };
    createdAt: Date;
    updatedAt: Date;
    updatedBy: {
        uid: string; // from logged-in user
        name: string;
        email: string;
    };
    isActive: "Yes" | "No"; // true if the activity is available for booking
  

}