export interface Ticket {
    id:string; //firestore Id
    ticketId: string; // auto generated by the server
    activity :{
        activityserviceId:string;
        activityName: string;

    };
    client:{
        name: string;
        clientId:string;
        pax:number;
        hotel:string;
        roomNumber:number;
        deposit:number;
        phone?: string;
        guideName:string;
        currency: 'USD' | 'Euro';
  
    };
    salePrice: number;
    commissionRate: number; // in percentage
    commissionAmount: number; // in currency
    costPriceAdult: number; // in currency
    costPriceChild: number; // in currency
    costPriceBaby: number; // in currency
    costPriceTotal: number; // in currency
    ticketTotalPrice: number; // in currency
    createdBy: {
        uid: string; // from logged-in user
        name: string; 
        email: string;
    };
    day:Date;
    Date:Date;
    createdAt: Date;
    updatedAt: Date;
    updatedBy: {
        uid: string; // from logged-in user
        name: string;
        email: string;
    };
   pickupPoint: string;
   pickupTime: string;
   guide: {
        guideId: string;
        guidePhone: string;
   }
  
  balance: 'Paid' | 'Unpaid';
  isActive: 'Yes' | 'No';
}